all:

include /usr/users/jdrexler/kaldi-sls/src/kaldi.mk


EXTRA_CXXFLAGS = -std=c++11

OBJFILES = hmm-gmm-boundary-sampler.o

LIBNAME = kaldi-baud

ADDLIBS = /usr/users/jdrexler/kaldi-sls/src/landmarks/kaldi-landmarks.a /usr/users/jdrexler/kaldi-sls/src/gmm/kaldi-gmm.a /usr/users/jdrexler/kaldi-sls/src/tree/kaldi-tree.a /usr/users/jdrexler/kaldi-sls/src/hmm/kaldi-hmm.a /usr/users/jdrexler/kaldi-sls/src/matrix/kaldi-matrix.a /usr/users/jdrexler/kaldi-sls/src/util/kaldi-util.a /usr/users/jdrexler/kaldi-sls/src/base/kaldi-base.a

include /usr/users/jdrexler/kaldi-sls/src/makefiles/default_rules.mk

#bin:

#EXTRA_CXXFLAGS = -Wno-sign-compare -std=c++11
#include /usr/users/dharwath/kaldi-sls/src/kaldi.mk

#BINFILES = hmm-gmm-sample-ali compute-ali-nmi segment-gmm-sample-ali segment-gmm-acc-stats-ali segment-gmm-init-mono

#OBJFILES =

#TESTFILES =

#ADDLIBS = kaldi-baud.a /usr/users/dharwath/kaldi-sls/src/landmarks/kaldi-landmarks.a /usr/users/dharwath/kaldi-sls/src/hmm/kaldi-hmm.a /usr/users/dharwath/kaldi-sls/src/gmm/kaldi-gmm.a /usr/users/dharwath/kaldi-sls/src/tree/kaldi-tree.a /usr/users/dharwath/kaldi-sls/src/thread/kaldi-thread.a /usr/users/dharwath/kaldi-sls/src/matrix/kaldi-matrix.a /usr/users/dharwath/kaldi-sls/src/util/kaldi-util.a /usr/users/dharwath/kaldi-sls/src/base/kaldi-base.a

#include /usr/users/dharwath/kaldi-sls/src/makefiles/default_rules.mk
